# Generated by Django 5.1.3 on 2025-07-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(blank=True, null=True)),
                ('by', models.CharField(max_length=100)),
                ('descendants', models.IntegerField()),
                ('hn_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
