# Generated by Django 5.1.3 on 2025-07-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='descendants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
