# Generated by Django 5.1.3 on 2025-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0002_alter_story_descendants'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
