# Generated by Django 5.1.3 on 2025-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0003_story_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
