# Generated by Django 5.1.3 on 2025-07-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0004_story_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(default='top', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
