# Generated by Django 5.2.4 on 2025-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0005_story_story_type_alter_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
