# Generated by Django 5.2.4 on 2025-07-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0008_alter_submitstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitstory',
            name='domain',
            field=models.CharField(blank=True, null=True),
        ),
    ]
